### ISSUE TITLE
Are older models completely incompatible with newer versions of flair?

### ISSUE THREAD

**Issue by hatrungduc** [zalandoresearch/flair#572]
I have a couple of sequence tagging models trained with Flair 0.4. Flair 0.4.1 was released and if I try to predict with these models now, exceptions are occuring:

The code
```python
from flair.models import SequenceTagger
from flair.data import Sentence

# load the model you trained
model = SequenceTagger.load_from_file('path/to/model_flair_0.4.pt')

sentence = Sentence('I love Berlin')

# predict tags and print
model.predict(sentence)

print(sentence.to_tagged_string())
```
produces
```
Traceback (most recent call last):
  File "~/flair/test_model.py", line 10, in <module>
    model.predict(sentence)
  File "~/virtualenvironments/flair/lib/python3.6/site-packages/flair/models/sequence_tagger_model.py", line 300, in predict
    tags, _ = self.forward_labels_and_loss(batch, sort=False)
  File "~/virtualenvironments/flair/lib/python3.6/site-packages/flair/models/sequence_tagger_model.py", line 268, in forward_labels_and_loss
    feature, lengths, tags = self.forward(sentences, sort=sort)
  File "~/virtualenvironments/flair/lib/python3.6/site-packages/flair/models/sequence_tagger_model.py", line 315, in forward
    self.embeddings.embed(sentences)
  File "~/virtualenvironments/flair/lib/python3.6/site-packages/flair/embeddings.py", line 130, in embed
    embedding.embed(sentences)
  File "~/virtualenvironments/flair/lib/python3.6/site-packages/flair/embeddings.py", line 63, in embed
    self._add_embeddings_internal(sentences)
  File "~/virtualenvironments/flair/lib/python3.6/site-packages/flair/embeddings.py", line 1143, in _add_embeddings_internal
    max([self.tokenizer.tokenize(sentence.to_tokenized_string()) for sentence in sentences], key=len))
  File "~/virtualenvironments/flair/lib/python3.6/site-packages/flair/embeddings.py", line 1143, in <listcomp>
    max([self.tokenizer.tokenize(sentence.to_tokenized_string()) for sentence in sentences], key=len))
  File "~/virtualenvironments/flair/lib/python3.6/site-packages/pytorch_pretrained_bert/tokenization.py", line 93, in tokenize
    for token in self.basic_tokenizer.tokenize(text):
  File "~/virtualenvironments/flair/lib/python3.6/site-packages/pytorch_pretrained_bert/tokenization.py", line 184, in tokenize
    if self.do_lower_case and token not in self.never_split:
AttributeError: 'BasicTokenizer' object has no attribute 'never_split'
```
Models trained with Flair 0.4.1 do not produce any errors. Is there anything I can do to make use of the older models? I suspect a problem with Flair using pytorch_pretrained_bert embeddings now. 
Thanks in advance!

**Comment by alanakbik** [comment]
Unfortunately, this is likely an issue with the serialized BertEmbeddings. If there are breaking changes between versions, de-serialization may not work. And since we upgraded `pytorch-pretrained-bert` from 0.3 to 0.6.1 between the releases, there are probably some breaking changes. Unfortunately, this may mean that you need to retrain the model :/

**Comment by hatrungduc** [comment]
Hello Alan,

Ah, thats what i was afraid would happen, but that's okay. Thank you for your answer
